name: Terraform Deployment

on:
    workflow_dispatch: {}


env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 # S3 bucket for the Terraform state
 BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}

jobs:
 terraform:
   name: "Terraform Infrastructure Change Deploy"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
 
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
 
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: 1.9.6

     - name: Create directory
       run: mkdir -p .terraform
       working-directory: infrastructure/aws/terraform

     - name: Terraform init
       id: init
       run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
       working-directory: infrastructure/aws/terraform
 
    #  - name: Terraform format
    #    id: fmt
    #    run: terraform fmt -check
    
     - name: Terraform validate
       id: validate
       run: terraform validate
       working-directory: infrastructure/aws/terraform
 
     - name: Terraform plan
       id: plan
       run: terraform plan -input=false
       working-directory: infrastructure/aws/terraform

     - name: Terraform apply
       run: terraform apply -auto-approve -input=false
       working-directory: infrastructure/aws/terraform